CREATE DATABASE IF NOT EXISTS training;
USE training;

CREATE TABLE IF NOT EXISTS training_records (
    training_id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id VARCHAR(10),
    course_name VARCHAR(100),
    training_hours INT,
    completion_status VARCHAR(50)
);

INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0227', 'Communication', 20, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0388', 'Excel Advanced', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0471', 'Project Management', 29, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0429', 'Excel Advanced', 33, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0358', 'Project Management', 26, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0149', 'Data Analysis', 10, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0228', 'Leadership', 23, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0328', 'Data Analysis', 26, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0194', 'Project Management', 6, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0407', 'Project Management', 37, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0031', 'Excel Advanced', 25, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0405', 'Communication', 17, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0073', 'Data Analysis', 5, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0030', 'Excel Advanced', 26, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0018', 'Communication', 16, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0003', 'Project Management', 33, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0100', 'Project Management', 24, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0380', 'Communication', 27, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0062', 'Leadership', 14, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0472', 'Excel Advanced', 21, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0054', 'Leadership', 22, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0442', 'Project Management', 18, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0300', 'Communication', 7, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0223', 'Data Analysis', 33, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0241', 'Leadership', 5, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0375', 'Project Management', 8, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0266', 'Project Management', 21, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0238', 'Leadership', 22, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0030', 'Excel Advanced', 31, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0453', 'Leadership', 36, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0366', 'Project Management', 31, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0496', 'Data Analysis', 28, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0168', 'Leadership', 27, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0495', 'Excel Advanced', 16, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0490', 'Project Management', 24, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0270', 'Leadership', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0471', 'Communication', 9, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0497', 'Leadership', 6, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0440', 'Project Management', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0263', 'Project Management', 11, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0013', 'Data Analysis', 25, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0166', 'Data Analysis', 21, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0400', 'Project Management', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0373', 'Project Management', 32, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0088', 'Project Management', 33, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0138', 'Leadership', 5, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0441', 'Leadership', 24, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0469', 'Data Analysis', 33, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0192', 'Data Analysis', 31, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0275', 'Data Analysis', 36, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0152', 'Excel Advanced', 29, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0043', 'Project Management', 17, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0226', 'Leadership', 31, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0154', 'Project Management', 10, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0173', 'Communication', 32, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0043', 'Leadership', 23, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0294', 'Project Management', 23, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0481', 'Leadership', 31, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0209', 'Communication', 32, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0137', 'Excel Advanced', 8, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0361', 'Communication', 8, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0077', 'Project Management', 26, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0451', 'Leadership', 34, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0043', 'Leadership', 30, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0033', 'Excel Advanced', 26, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0495', 'Leadership', 8, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0135', 'Excel Advanced', 10, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0061', 'Project Management', 28, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0105', 'Excel Advanced', 28, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0058', 'Leadership', 39, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0341', 'Data Analysis', 9, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0082', 'Excel Advanced', 11, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0276', 'Communication', 39, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0170', 'Data Analysis', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0263', 'Data Analysis', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0103', 'Excel Advanced', 18, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0373', 'Leadership', 33, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0263', 'Leadership', 22, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0384', 'Excel Advanced', 27, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0460', 'Data Analysis', 15, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0479', 'Leadership', 7, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0495', 'Excel Advanced', 15, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0386', 'Project Management', 14, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0047', 'Data Analysis', 13, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0476', 'Excel Advanced', 34, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0475', 'Leadership', 19, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0456', 'Project Management', 33, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0233', 'Communication', 21, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0035', 'Data Analysis', 27, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0458', 'Leadership', 17, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0041', 'Leadership', 24, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0330', 'Excel Advanced', 17, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0182', 'Leadership', 26, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0421', 'Data Analysis', 36, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0056', 'Project Management', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0148', 'Project Management', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0290', 'Communication', 11, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0111', 'Communication', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0305', 'Communication', 36, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0441', 'Project Management', 19, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0049', 'Project Management', 31, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0179', 'Leadership', 19, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0293', 'Project Management', 12, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0198', 'Communication', 9, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0434', 'Project Management', 13, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0342', 'Project Management', 7, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0216', 'Project Management', 22, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0139', 'Project Management', 38, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0164', 'Leadership', 16, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0323', 'Leadership', 35, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0317', 'Leadership', 35, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0038', 'Excel Advanced', 10, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0012', 'Communication', 32, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0318', 'Leadership', 24, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0118', 'Data Analysis', 28, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0102', 'Communication', 22, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0487', 'Project Management', 8, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0116', 'Project Management', 19, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0105', 'Data Analysis', 34, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0150', 'Data Analysis', 12, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0092', 'Excel Advanced', 6, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0467', 'Project Management', 27, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0465', 'Communication', 8, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0093', 'Excel Advanced', 22, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0079', 'Data Analysis', 31, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0117', 'Data Analysis', 25, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0437', 'Project Management', 8, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0222', 'Excel Advanced', 39, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0305', 'Leadership', 27, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0294', 'Leadership', 18, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0264', 'Leadership', 34, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0096', 'Data Analysis', 9, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0046', 'Project Management', 18, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0027', 'Communication', 17, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0359', 'Communication', 15, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0213', 'Leadership', 35, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0209', 'Excel Advanced', 11, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0480', 'Leadership', 33, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0083', 'Leadership', 24, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0090', 'Project Management', 13, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0062', 'Excel Advanced', 23, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0410', 'Project Management', 15, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0002', 'Communication', 13, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0033', 'Data Analysis', 32, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0278', 'Leadership', 19, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0086', 'Data Analysis', 31, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0160', 'Leadership', 20, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0177', 'Communication', 16, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0088', 'Project Management', 21, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0406', 'Communication', 40, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0043', 'Excel Advanced', 36, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0322', 'Communication', 40, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0084', 'Communication', 10, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0424', 'Leadership', 27, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0429', 'Excel Advanced', 16, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0320', 'Excel Advanced', 7, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0006', 'Project Management', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0141', 'Leadership', 32, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0362', 'Leadership', 40, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0279', 'Project Management', 36, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0246', 'Data Analysis', 31, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0260', 'Leadership', 9, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0471', 'Communication', 8, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0072', 'Excel Advanced', 14, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0138', 'Data Analysis', 23, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0298', 'Data Analysis', 20, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0248', 'Excel Advanced', 28, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0453', 'Leadership', 33, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0116', 'Project Management', 26, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0075', 'Data Analysis', 29, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0393', 'Excel Advanced', 22, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0185', 'Communication', 5, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0060', 'Project Management', 33, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0146', 'Data Analysis', 34, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0061', 'Data Analysis', 21, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0474', 'Project Management', 35, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0150', 'Data Analysis', 33, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0354', 'Project Management', 38, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0345', 'Communication', 33, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0445', 'Excel Advanced', 8, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0122', 'Communication', 23, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0358', 'Excel Advanced', 31, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0272', 'Communication', 14, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0239', 'Project Management', 39, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0489', 'Excel Advanced', 7, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0045', 'Project Management', 33, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0268', 'Excel Advanced', 19, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0382', 'Excel Advanced', 17, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0338', 'Excel Advanced', 6, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0340', 'Data Analysis', 35, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0135', 'Data Analysis', 18, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0337', 'Excel Advanced', 21, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0080', 'Leadership', 20, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0282', 'Excel Advanced', 31, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0306', 'Project Management', 21, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0457', 'Project Management', 19, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0386', 'Project Management', 7, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0423', 'Leadership', 14, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0231', 'Communication', 40, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0018', 'Data Analysis', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0300', 'Excel Advanced', 30, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0345', 'Communication', 14, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0402', 'Project Management', 30, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0026', 'Data Analysis', 22, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0121', 'Project Management', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0393', 'Leadership', 6, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0020', 'Data Analysis', 38, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0142', 'Project Management', 31, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0229', 'Communication', 14, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0461', 'Excel Advanced', 25, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0483', 'Excel Advanced', 31, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0044', 'Excel Advanced', 25, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0320', 'Project Management', 12, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0299', 'Project Management', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0360', 'Project Management', 21, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0439', 'Project Management', 35, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0390', 'Data Analysis', 35, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0279', 'Leadership', 21, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0264', 'Excel Advanced', 19, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0485', 'Excel Advanced', 35, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0338', 'Communication', 33, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0500', 'Data Analysis', 30, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0408', 'Communication', 7, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0094', 'Data Analysis', 10, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0093', 'Project Management', 5, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0020', 'Communication', 11, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0153', 'Project Management', 16, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0404', 'Excel Advanced', 27, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0461', 'Leadership', 36, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0010', 'Project Management', 34, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0479', 'Leadership', 38, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0135', 'Project Management', 11, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0010', 'Project Management', 22, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0127', 'Excel Advanced', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0324', 'Communication', 6, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0247', 'Leadership', 25, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0457', 'Excel Advanced', 5, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0098', 'Data Analysis', 27, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0442', 'Project Management', 13, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0333', 'Project Management', 37, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0231', 'Data Analysis', 17, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0377', 'Leadership', 15, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0097', 'Leadership', 12, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0371', 'Project Management', 13, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0330', 'Data Analysis', 25, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0097', 'Data Analysis', 8, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0279', 'Excel Advanced', 27, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0141', 'Leadership', 34, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0144', 'Excel Advanced', 13, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0179', 'Project Management', 14, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0074', 'Leadership', 35, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0469', 'Communication', 7, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0186', 'Data Analysis', 6, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0145', 'Project Management', 25, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0398', 'Leadership', 36, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0080', 'Project Management', 14, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0120', 'Excel Advanced', 6, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0104', 'Communication', 37, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0353', 'Leadership', 40, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0003', 'Excel Advanced', 15, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0232', 'Excel Advanced', 24, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0228', 'Leadership', 26, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0382', 'Excel Advanced', 26, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0258', 'Data Analysis', 14, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0192', 'Leadership', 26, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0474', 'Data Analysis', 15, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0257', 'Communication', 7, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0230', 'Excel Advanced', 5, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0387', 'Excel Advanced', 26, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0126', 'Data Analysis', 20, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0176', 'Project Management', 39, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0083', 'Leadership', 28, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0350', 'Communication', 25, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0112', 'Excel Advanced', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0269', 'Project Management', 22, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0047', 'Data Analysis', 20, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0269', 'Project Management', 36, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0406', 'Excel Advanced', 21, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0223', 'Excel Advanced', 25, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0448', 'Communication', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0022', 'Excel Advanced', 6, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0491', 'Leadership', 16, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0010', 'Data Analysis', 35, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0311', 'Data Analysis', 39, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0435', 'Excel Advanced', 6, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0104', 'Leadership', 8, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0337', 'Data Analysis', 27, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0394', 'Communication', 32, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0096', 'Excel Advanced', 5, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0250', 'Excel Advanced', 36, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0146', 'Communication', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0207', 'Project Management', 23, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0125', 'Data Analysis', 30, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0338', 'Excel Advanced', 36, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0121', 'Excel Advanced', 14, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0358', 'Data Analysis', 37, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0370', 'Data Analysis', 25, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0413', 'Data Analysis', 12, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0482', 'Communication', 24, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0046', 'Data Analysis', 32, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0442', 'Communication', 21, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0259', 'Data Analysis', 28, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0419', 'Project Management', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0170', 'Data Analysis', 28, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0050', 'Communication', 39, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0010', 'Leadership', 25, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0142', 'Project Management', 5, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0449', 'Project Management', 22, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0112', 'Data Analysis', 26, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0195', 'Project Management', 34, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0011', 'Communication', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0438', 'Project Management', 34, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0275', 'Communication', 11, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0277', 'Excel Advanced', 18, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0423', 'Communication', 34, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0133', 'Leadership', 9, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0469', 'Project Management', 15, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0410', 'Leadership', 34, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0153', 'Data Analysis', 24, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0425', 'Excel Advanced', 30, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0040', 'Communication', 32, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0106', 'Leadership', 14, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0354', 'Project Management', 23, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0300', 'Communication', 5, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0090', 'Leadership', 24, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0325', 'Project Management', 34, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0129', 'Excel Advanced', 22, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0193', 'Excel Advanced', 11, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0145', 'Excel Advanced', 26, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0110', 'Data Analysis', 7, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0380', 'Leadership', 28, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0213', 'Excel Advanced', 38, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0450', 'Excel Advanced', 35, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0276', 'Data Analysis', 19, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0268', 'Leadership', 37, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0160', 'Data Analysis', 34, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0287', 'Data Analysis', 11, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0497', 'Leadership', 17, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0480', 'Data Analysis', 33, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0488', 'Excel Advanced', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0107', 'Excel Advanced', 10, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0002', 'Project Management', 37, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0291', 'Data Analysis', 36, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0226', 'Communication', 39, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0421', 'Excel Advanced', 38, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0047', 'Communication', 9, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0462', 'Leadership', 9, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0051', 'Data Analysis', 17, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0262', 'Excel Advanced', 8, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0047', 'Data Analysis', 5, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0057', 'Communication', 13, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0377', 'Communication', 9, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0176', 'Project Management', 17, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0065', 'Project Management', 38, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0026', 'Excel Advanced', 15, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0429', 'Leadership', 32, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0223', 'Leadership', 10, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0431', 'Excel Advanced', 22, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0083', 'Excel Advanced', 6, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0423', 'Excel Advanced', 12, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0169', 'Excel Advanced', 5, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0205', 'Data Analysis', 27, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0184', 'Communication', 23, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0053', 'Data Analysis', 40, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0339', 'Leadership', 24, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0476', 'Communication', 9, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0402', 'Leadership', 9, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0104', 'Project Management', 20, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0061', 'Leadership', 9, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0263', 'Communication', 34, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0314', 'Communication', 7, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0468', 'Project Management', 11, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0201', 'Data Analysis', 7, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0011', 'Data Analysis', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0137', 'Data Analysis', 20, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0137', 'Leadership', 8, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0176', 'Data Analysis', 9, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0292', 'Project Management', 10, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0478', 'Leadership', 12, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0015', 'Data Analysis', 38, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0330', 'Data Analysis', 23, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0061', 'Communication', 20, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0076', 'Excel Advanced', 28, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0356', 'Project Management', 17, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0176', 'Communication', 6, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0130', 'Leadership', 29, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0316', 'Project Management', 24, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0267', 'Excel Advanced', 39, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0257', 'Data Analysis', 18, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0265', 'Excel Advanced', 22, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0050', 'Data Analysis', 34, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0059', 'Communication', 12, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0114', 'Data Analysis', 18, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0335', 'Communication', 29, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0346', 'Project Management', 7, 'Not Started');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0031', 'Project Management', 6, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0429', 'Project Management', 20, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0326', 'Communication', 18, 'Completed');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0460', 'Project Management', 19, 'In Progress');
INSERT INTO training_records (employee_id, course_name, training_hours, completion_status) VALUES ('E0462', 'Communication', 28, 'In Progress');